Repository MicrosoftDocs/sdk-api, pull requests merged in 2020-01, with the labels that each got.

#16 Fix doc on GetIpErrorString's Size parameter
  sdk-api-src/content/iphlpapi/nf-iphlpapi-getiperrorstring.md
Labels: do-not-merge, review-team-triage

#30 Setsockopt not supported while connecting
  sdk-api-src/content/winsock2/nf-winsock2-connect.md
Labels: do-not-merge, review-team-triage

#31 Remove spurious a> characters
  sdk-api-src/content/winsock2/nf-winsock2-wsapoll.md
Labels: do-not-merge

#32 Fix invalid FD docs
  sdk-api-src/content/winsock2/nf-winsock2-wsapoll.md
Labels: do-not-merge, review-team-triage

#8 Update nf-memoryapi-virtualalloc2.md
  sdk-api-src/content/memoryapi/nf-memoryapi-virtualalloc2.md
Labels: do-not-merge, review-team-triage

#14 Update nf-handleapi-duplicatehandle.md
  sdk-api-src/content/handleapi/nf-handleapi-duplicatehandle.md
Labels: do-not-merge, review-team-triage

#15 Update nf-sysinfoapi-getintegrateddisplaysize.md
  sdk-api-src/content/sysinfoapi/nf-sysinfoapi-getintegrateddisplaysize.md
Labels: do-not-merge, review-team-triage

#12 Update ne-mfidl-mfstreamsink_marker_type.md
  sdk-api-src/content/mfidl/ne-mfidl-mfstreamsink_marker_type.md
Labels: do-not-merge, review-team-triage

#35 Specify correct order of flips and rotations
  sdk-api-src/content/wincodec/nn-wincodec-iwicbitmapfliprotator.md
Labels: do-not-merge, review-team-triage

#18 update MagSetWindowFilterList flag notes
  sdk-api-src/content/magnification/nf-magnification-magsetwindowfilterlist.md
Labels: do-not-merge, review-team-triage

#22 Fixed formatting and grammar.
  sdk-api-src/content/winuser/nf-winuser-setwindowdisplayaffinity.md
Labels: do-not-merge, review-team-triage

#28 Fixed CreateTimerQueueTimer parameter order
  sdk-api-src/content/threadpoollegacyapiset/nf-threadpoollegacyapiset-createtimerqueuetimer.md
Labels: do-not-merge, review-team-triage

#19 â€“ seems like something like "i.e." for clarify
  sdk-api-src/content/objbase/ne-objbase-coinit.md
Labels: do-not-merge, review-team-triage

#23 Corrected description of FirstElement in the D3D11_BUFFER_SRV structure
  sdk-api-src/content/d3d11/ns-d3d11-d3d11_buffer_srv.md
Labels: do-not-merge, review-team-triage

#20 Added semantic of D3D12_BUFFER_UAV::StructureByteStride
  sdk-api-src/content/d3d12/ns-d3d12-d3d12_buffer_uav.md
Labels: do-not-merge, review-team-triage

#10 NETRESOURCE URL fix
  sdk-api-src/content/winnetwk/nf-winnetwk-wnetaddconnection2a.md
Labels: do-not-merge, review-team-triage

#9 NETRESOURCE URL fix
  sdk-api-src/content/winnetwk/nf-winnetwk-wnetenumresourcea.md
Labels: do-not-merge, review-team-triage

#36 Updating Creduipromptforcredentials flags
  sdk-api-src/content/wincred/nf-wincred-creduipromptforwindowscredentialsa.md
  sdk-api-src/content/wincred/nf-wincred-creduipromptforwindowscredentialsw.md
Labels: do-not-merge, review-team-triage

#38 Escape backslashes in extended length prefix
  sdk-api-src/content/fileapi/nf-fileapi-setfileattributesw.md
Labels: do-not-merge, review-team-triage

#27 Escape backslashes in GetDiskFreeSpace[Ex] docs
  sdk-api-src/content/fileapi/nf-fileapi-getdiskfreespacea.md
  sdk-api-src/content/fileapi/nf-fileapi-getdiskfreespaceexa.md
  sdk-api-src/content/fileapi/nf-fileapi-getdiskfreespaceexw.md
  sdk-api-src/content/fileapi/nf-fileapi-getdiskfreespacew.md
Labels: do-not-merge, review-team-triage

#26 Fix some improper escaping
  sdk-api-src/content/processthreadsapi/nf-processthreadsapi-setthreadpriority.md
Labels: do-not-merge, review-team-triage

#40 Updated ID3D12Device::CreateSharedHandle
  sdk-api-src/content/d3d12/nf-d3d12-id3d12device-createsharedhandle.md
Labels: do-not-merge, review-team-triage

#39 Updated description for ID3D11Fence::CreateSharedHandle
  sdk-api-src/content/d3d11_3/nf-d3d11_3-id3d11fence-createsharedhandle.md
Labels: do-not-merge, review-team-triage

#44 Update nf-synchapi-createwaitabletimerw.md
  sdk-api-src/content/synchapi/nf-synchapi-createwaitabletimerw.md
Labels: do-not-merge, review-team-triage

#42 Update nf-synchapi-initonceexecuteonce.md
  sdk-api-src/content/synchapi/nf-synchapi-initonceexecuteonce.md
Labels: do-not-merge, review-team-triage

#41 incorrect escaping in GetVolumeNameForVolumeMountPointW
  sdk-api-src/content/fileapi/nf-fileapi-getvolumenameforvolumemountpointw.md
Labels: do-not-merge, review-team-triage

#37 Update nf-combaseapi-cogetclassobject.md
  sdk-api-src/content/combaseapi/nf-combaseapi-cogetclassobject.md
Labels: do-not-merge, review-team-triage

#47 Update nf-wlanapi-wlangetavailablenetworklist.md
  sdk-api-src/content/wlanapi/nf-wlanapi-wlangetavailablenetworklist.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#24 Make trailing \ noticeable
  sdk-api-src/content/shlobj_core/nf-shlobj_core-shgetfolderpathw.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#25 Remove trailing `a>` from link
  sdk-api-src/content/shobjidl_core/nf-shobjidl_core-ivirtualdesktopmanager-movewindowtodesktop.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#13 Removed trailing 'a>' HTML residue
  sdk-api-src/content/synchapi/nf-synchapi-createwaitabletimerw.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#48 Clarify behavior of GetWindowTextLength towards zero-length titles
  sdk-api-src/content/winuser/nf-winuser-getwindowtextlengtha.md
  sdk-api-src/content/winuser/nf-winuser-getwindowtextlengthw.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#43 Update ni-winioctl-fsctl_get_reparse_point.md
  sdk-api-src/content/winioctl/ni-winioctl-fsctl_get_reparse_point.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#45 Fix formatting in FSCTL_DISMOUNT_VOLUME
  sdk-api-src/content/winioctl/ni-winioctl-fsctl_dismount_volume.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#49 remove visible tag from content
  sdk-api-src/content/winuser/nf-winuser-systemparametersinfoa.md
  sdk-api-src/content/winuser/nf-winuser-systemparametersinfow.md
Labels: Change sent to author, desktop/prod, sdk-api-reference/tech

#50 Update nn-uiautomationcore-iaccessibleex.md
  sdk-api-src/content/uiautomationcore/nn-uiautomationcore-iaccessibleex.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#51 Add docs for IHandlerActivationHost methods, mention handlerInfo supports IObjectWithSelection
  sdk-api-src/content/shobjidl_core/nf-shobjidl_core-ihandleractivationhost-beforecocreateinstance.md
  sdk-api-src/content/shobjidl_core/nf-shobjidl_core-ihandleractivationhost-beforecreateprocess.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#55 Removed leftover from copy-paste
  sdk-api-src/content/objidl/nf-objidl-ibindctx-setbindoptions.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#56 Missing backslash in volume GUID syntax
  sdk-api-src/content/winbase/nf-winbase-setvolumemountpointa.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#57 missing slashes on Volume GUID path
  sdk-api-src/content/winbase/nf-winbase-setvolumemountpointw.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#53 Fixed missing escape sequence for '\' characters.
  sdk-api-src/content/winsvc/ns-winsvc-query_service_configa.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#52 Fixing minor spelling mistake
  sdk-api-src/content/projectedfslib/nf-projectedfslib-prjstartvirtualizing.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#46 Replaced visible `<i>` with a markdown code syntax
  sdk-api-src/content/winsvc/nf-winsvc-createservicew.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#29 Fix typos on QUERY_CHANGES_VIRTUAL_DISK_RANGE doc
  sdk-api-src/content/virtdisk/ns-virtdisk-query_changes_virtual_disk_range.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#17 Fix bad escape
  sdk-api-src/content/wincred/ns-wincred-credentialw.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#11 Fix link to GetEnvironmentStrings doc
  sdk-api-src/content/winbase/nf-winbase-getenvironmentvariable.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#21 Update nf-ntdef-initializeobjectattributes.md
  sdk-api-src/content/ntdef/nf-ntdef-initializeobjectattributes.md
Labels: Change sent to author, desktop/prod, do-not-merge, review-team-triage, sdk-api-reference/tech

#59 PD_NOPAGENUMS is 8 not 2
  sdk-api-src/content/commdlg/ns-commdlg-printdlga.md
  sdk-api-src/content/commdlg/ns-commdlg-printdlgw.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#61 Update nf-uiautomationcoreapi-uiaraisenotificationevent.md
  sdk-api-src/content/uiautomationcoreapi/nf-uiautomationcoreapi-uiaraisenotificationevent.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#60 Correct mistaken cchFilePath parameter description
  sdk-api-src/content/fileapi/nf-fileapi-getfinalpathnamebyhandlea.md
  sdk-api-src/content/fileapi/nf-fileapi-getfinalpathnamebyhandlew.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech

#62 Update nf-d3d10shader-id3d10shaderreflectiontype-getmembertypename.md
  sdk-api-src/content/d3d10shader/nf-d3d10shader-id3d10shaderreflectiontype-getmembertypename.md
Labels: Change sent to author, desktop/prod, do-not-merge, sdk-api-reference/tech
